Netflix/eureka

eureka-dashboard/src/main/resources/clusters-view.js, eureka-dashboard/src/main/resources/clusters.html
1. write and read clusters nested rings visualization
2. interactively display eureka server instance info (vip, hostname, ip, status, ports)
=> nested cluster ring 

eureka-client/src/test/java/com/netflix/eureka2/client/channel/InterestChannelImplTest.java, eureka-integration/src/main/java/com/netflix/eureka2/integration/WriteClusterIntegrationTest.java, eureka-integration/src/main/java/com/netflix/eureka2/integration/WriteServerIntegrationTest.java, eureka-test-utils/src/main/java/com/netflix/eureka2/rx/ExtTestSubscriber.java, settings.gradle
the module itself was removed some time ago
=> 2.x Remove eureka-ocelli module reference from settings.gradle 

eureka-client/src/main/java/com/netflix/appinfo/AmazonInfo.java
=> Fixes for clean connection close in AmazonInfo when reading from the AWS

eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java
InstanceInfo.Builder.setLeaseInstance broke the builder pattern by declaring to return void. This simple commit fixes it to return Builder.
=> Fix InstanceInfo.Builder.setLeaseInstance

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java, eureka-client/src/main/java/com/netflix/discovery/shared/Applications.java
More String.toUpperCase() fixes.
=> More toUpperCase() fixes

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
Compare data center name object with its name rather than instance of data center object itself.
=> Objects of different types compared with equals method.

eureka2-core/src/main/java/com/netflix/eureka2/utils/rx/ResourceObservable.java, eureka2-core/src/test/java/com/netflix/eureka2/utils/rx/ResourceObservableTest.java, eureka2-test-utils/src/main/java/com/netflix/eureka2/rx/ExtTestSubscriber.java
Handle properly recoverable and non-recoverable errors.
=> Fix bug #448

eureka-core/src/main/java/com/netflix/eureka/RemoteRegionRegistry.java
Wrap around the TimedSupervisorTask for better reliability.
The remoteRegionFetchExecutor can have a max of 2 concurrent threads executing a remote region fetch.
=> 1.x Wrapping RemoteRegionFetch in TimedSupervisorTask

eureka2-core/src/main/java/com/netflix/eureka2/registry/NotifyingInstanceInfoHolder.java, eureka2-core/src/test/java/com/netflix/eureka2/registry/NotifyingInstanceInfoHolderTest.java, eureka2-core/src/test/java/com/netflix/eureka2/registry/SourcedEurekaRegistryImplTest.java
This is done to fix the following race condition:
1. Write Servers A and B replicate to each other
2. Instance X registers with server A (A -> X local, B -> X replicated)
3. Instance X registration channel close and reconnect to server B
3a. A put X local into eviction queue
3b. B put X replicated into eviction queue
4. X register an unchanged instanceInfo to server B
4a. B's holder add X as a second copy as the original replicated copy is yet to be evicted
4b. Because the B holder's copies diff to empty delta, a CN with source local is never published
5. B's senderReplicationChannel disconnects and reconnects to A
5a. B's initState never sees the new X local as the CN is never published, resulting in X
not replicating to server A.
=> 2.x NotifyingInstanceInfoHolder eagerly promote updates from local source to snapshot if current snapshot is not from local source

build.gradle, eureka-client/build.gradle, eureka-client/src/main/java/com/netflix/appinfo/EurekaClientIdentity.java, eureka-client/src/main/java/com/netflix/discovery/DefaultEurekaClientConfig.java, eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java, eureka-client/src/main/java/com/netflix/discovery/DnsResolver.java, eureka-client/src/main/java/com/netflix/discovery/EurekaClientConfig.java, eureka-client/src/main/java/com/netflix/discovery/shared/EurekaJerseyClient.java, eureka-client/src/test/java/com/netflix/discovery/AbstractDiscoveryClientTester.java, eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientRedirectTest.java, eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientRule.java, eureka-client/src/test/java/com/netflix/discovery/MockRemoteEurekaServer.java, eureka-client/src/test/java/com/netflix/discovery/util/ApplicationFunctions.java, eureka-client/src/test/java/com/netflix/discovery/util/InstanceInfoGenerator.java
Initial implementation for discussion. Unit tests missing.
=> 1.x Pin client to the redirected address.

eureka2-client/build.gradle, eureka2-core/build.gradle, eureka2-integration/build.gradle, eureka2-server/build.gradle, eureka2-test-utils/build.gradle, eureka2-testkit/build.gradle, eureka2-write-server/src/main/java/com/netflix/eureka2/server/config/WriteServerConfig.java
Branch name is mis-leading, as rxnetty was not actually easily shadeable. Users of eureka2-client will need to to do the shade.
=> 2x shade ocelli

eureka2-core/src/main/java/com/netflix/eureka2/metric/MessageConnectionMetrics.java, eureka2-core/src/main/java/com/netflix/eureka2/metric/noop/NoOpMessageConnectionMetrics.java, eureka2-core/src/main/java/com/netflix/eureka2/transport/base/BaseMessageConnection.java, eureka2-core/src/test/java/com/netflix/eureka2/transport/base/BaseMessageConnectionTest.java, eureka2-metrics-spectator/src/main/java/com/netflix/eureka2/metric/SpectatorMessageConnectionMetrics.java, eureka2-server/src/main/java/com/netflix/eureka2/server/health/EurekaHealthStatusModule.java, eureka2-testkit/src/main/java/com/netflix/eureka2/testkit/cli/Session.java
Bug fix in EurekaHealthStatusModule module.
=> 2.x Safer implementation of ack handling + pending ack queue size monitor.

eureka-client/src/main/java/com/netflix/appinfo/ApplicationInfoManager.java, eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java, eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientRegisterUpdateTest.java, eureka-core/src/main/java/com/netflix/eureka/PeerAwareInstanceRegistry.java, eureka-core/src/main/java/com/netflix/eureka/lease/Lease.java, eureka-core/src/main/java/com/netflix/eureka/util/AwsAsgUtil.java
Also fixes for issues #531 and #533
=> Various fixes (specifics in commit log)

eureka-core/src/main/java/com/netflix/eureka/InstanceRegistry.java, eureka-core/src/main/java/com/netflix/eureka/resources/ASGResource.java, eureka-core/src/main/java/com/netflix/eureka/util/AwsAsgUtil.java
- async load data from the asgCache for isASGEnabled queries.
- avoid using expensive getASGAccount(asgName) if possible.
=> AwsAsgUtil fixes

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java, eureka-client/src/main/java/com/netflix/discovery/StatusChangeEvent.java, eureka-client/src/test/java/com/netflix/discovery/AbstractDiscoveryClientTester.java, eureka-client/src/test/java/com/netflix/discovery/BackUpRegistryTest.java, eureka-client/src/test/java/com/netflix/discovery/BaseDiscoveryClientTester.java, eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientEventBusTest.java, eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientRegisterUpdateTest.java, eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientRule.java, eureka-client/src/test/java/com/netflix/discovery/MockRemoteEurekaServer.java, eureka-client/src/test/java/com/netflix/discovery/guice/EurekaModuleTest.java, eureka-core/src/test/java/com/netflix/eureka/AbstractTester.java, eureka-examples/src/main/java/com/netflix/eureka/ExampleEurekaGovernatedService.java
Also added tests for eventBus events
=> Clean up of static usage of ApplicationInfoManager in DiscoveryClient

eureka-core/src/main/java/com/netflix/eureka/util/StatusInfo.java
StatusInfo's serializer should be 'com.netflix.discovery...' instead of
'com.netflix.eureka...'
=> fixed package name of serializer

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java, eureka-client/src/main/java/com/netflix/discovery/converters/EurekaJacksonCodec.java
Make EurekaJacksonCodec more inline with Converters with public static classes to extend.
Make EurekaJacksonCodec.INSTANCE mutable.
Add get/set to DiscoveryClientOptionalArgs.
I'd rather not have a static instance in EurekaJacksonCodec, suggestions welcome.
=> Refactor so other DI Systems can extend eureka.

build.gradle, eureka-client/build.gradle, eureka-client/src/main/java/com/netflix/appinfo/ApplicationInfoManager.java, eureka-client/src/main/java/com/netflix/appinfo/CloudInstanceConfig.java, eureka-client/src/main/java/com/netflix/appinfo/MyDataCenterInstanceConfig.java, eureka-client/src/main/java/com/netflix/appinfo/providers/EurekaConfigBasedInstanceInfoProvider.java, eureka-client/src/main/java/com/netflix/discovery/DefaultEurekaClientConfig.java, eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java, eureka-client/src/main/java/com/netflix/discovery/EurekaUpStatusResolver.java, eureka-client/src/main/java/com/netflix/discovery/InternalEurekaStatusModule.java, eureka-client/src/main/java/com/netflix/discovery/converters/CodecWrapper.java, eureka-client/src/main/java/com/netflix/discovery/converters/jackson/EurekaJacksonCodecNG.java, eureka-client/src/main/java/com/netflix/discovery/converters/jackson/InstanceInfoBeanDeserializers.java, eureka-client/src/main/java/com/netflix/discovery/converters/jackson/MiniInstanceInfoMixIn.java, eureka-client/src/main/java/com/netflix/discovery/provider/DiscoveryJerseyProvider.java, eureka-client/src/test/java/com/netflix/discovery/converters/EurekaCodecCompatibilityTest.java, eureka-client/src/test/java/com/netflix/discovery/converters/EurekaEntityComparators.java, eureka-client/src/test/java/com/netflix/discovery/converters/EurekaJacksonCodecNGTest.java, eureka-core/build.gradle, eureka-core/src/main/java/com/netflix/eureka/AbstractInstanceRegistry.java, eureka-core/src/main/java/com/netflix/eureka/InstanceRegistry.java, eureka-core/src/main/java/com/netflix/eureka/cluster/PeerEurekaNode.java, eureka-core/src/main/java/com/netflix/eureka/resources/InstanceResource.java, eureka-core/src/main/java/com/netflix/eureka/resources/ServerInfoResource.java, eureka-examples/build.gradle, eureka-examples/src/main/java/com/netflix/eureka/ExampleEurekaGovernatedService.java, eureka-examples/src/main/java/com/netflix/eureka/ExampleServiceBase.java
* Adding mini jackson deserialization to the codec sets
* sync with master
=> Adding mini jackson deserialization to the codec sets

build.gradle, eureka2-server/src/main/java/com/netflix/eureka2/server/http/EurekaHttpServer.java, eureka2-server/src/main/java/com/netflix/eureka2/server/http/JarResourcesRequestHandler.java, eureka2-server/src/main/java/com/netflix/eureka2/server/http/proxy/HttpRequestDispatcher.java, eureka2-server/src/test/java/com/netflix/eureka2/server/http/JarResourcesRequestHandlerTest.java, eureka2-write-server/build.gradle, eureka2-write-server/src/main/java/com/netflix/eureka2/server/rest/WriteServerRootResource.java, gradle.properties
eureka-ui is SNAPSHOT dependency until first RC is available.
=> 2.x Integrate eureka-ui WEB UI with write server

eureka2-core/src/main/java/com/netflix/eureka2/registry/SourcedEurekaRegistryImpl.java
by onError emitted by a registration observable.
=> 2.x Registry update that protects merge subject from being terminated

eureka-client-archaius2/src/main/java/com/netflix/discovery/EurekaArchaius2InstanceConfig.java, eureka-client/src/main/java/com/netflix/appinfo/AbstractInstanceConfig.java, eureka-client/src/main/java/com/netflix/appinfo/CloudInstanceConfig.java, eureka-client/src/main/java/com/netflix/appinfo/EurekaInstanceConfig.java, eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java, eureka-client/src/main/java/com/netflix/appinfo/MyDataCenterInstanceConfig.java, eureka-client/src/main/java/com/netflix/appinfo/PropertiesInstanceConfig.java, eureka-client/src/main/java/com/netflix/appinfo/providers/EurekaConfigBasedInstanceInfoProvider.java, eureka-client/src/main/java/com/netflix/discovery/converters/jackson/mixin/MiniInstanceInfoMixIn.java, eureka-client/src/test/java/com/netflix/appinfo/InstanceInfoTest.java, eureka-test-utils/src/main/java/com/netflix/discovery/util/InstanceInfoGenerator.java
For compatibility ease, reusing the deprecated "sid" (serviceId) field.
Also some minor reformatting.
=> Decoupling the id of InstanceInfo from the id of the DataCenterInfo.

eureka-client/src/main/java/com/netflix/discovery/provider/DiscoveryJerseyProvider.java
issue: https://github.com/Netflix/eureka/issues/647
=> 1.x Better error handling for invalid content in request

eureka-client-archaius2/src/main/java/com/netflix/discovery/EurekaArchaius2ClientConfig.java, eureka-client/src/main/java/com/netflix/discovery/DefaultEurekaClientConfig.java, eureka-client/src/main/java/com/netflix/discovery/EurekaClientConfig.java, eureka-core/src/main/java/com/netflix/eureka/AbstractInstanceRegistry.java, eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerConfig.java, eureka-core/src/main/java/com/netflix/eureka/EurekaServerConfig.java, eureka-core/src/main/java/com/netflix/eureka/PeerAwareInstanceRegistryImpl.java
Experimental feature with no cancellation replication for evicted items.
Imposing additional eviction constraints, based on registry size not
received heartbeats.
=> 1.x Eviction mechanism update

eureka-client/src/main/java/com/netflix/appinfo/AmazonInfo.java, eureka-core/build.gradle, eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerConfig.java, eureka-core/src/main/java/com/netflix/eureka/EurekaBootStrap.java, eureka-core/src/main/java/com/netflix/eureka/EurekaServerConfig.java, eureka-core/src/main/java/com/netflix/eureka/aws/AwsBinder.java, eureka-core/src/main/java/com/netflix/eureka/aws/AwsBinderDelegate.java, eureka-core/src/main/java/com/netflix/eureka/aws/AwsBindingStrategy.java, eureka-core/src/main/java/com/netflix/eureka/aws/EIPManager.java, eureka-core/src/main/java/com/netflix/eureka/aws/Route53Binder.java
rebase route53 change https://github.com/Netflix/eureka/pull/659
to di-friendly-server
=> add route53 binding alternative to eip

eureka-client-archaius2/src/main/java/com/netflix/discovery/shared/transport/EurekaArchaius2TransportConfig.java, eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java, eureka-client/src/main/java/com/netflix/discovery/shared/resolver/AsyncResolver.java, eureka-client/src/main/java/com/netflix/discovery/shared/resolver/aws/ConfigClusterResolver.java, eureka-client/src/main/java/com/netflix/discovery/shared/transport/DefaultEurekaTransportConfig.java, eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaHttpClients.java, eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaTransportConfig.java, eureka-client/src/main/java/com/netflix/discovery/util/ThresholdLevelsMetric.java, eureka-client/src/test/java/com/netflix/discovery/shared/resolver/aws/ConfigClusterResolverTest.java, eureka-core/src/main/java/com/netflix/eureka/resources/InstanceResource.java
- update staleness monitor levels if registry fetch never worked
- Provide a mechanism to use new transport with bootstrap servers for query
- Tune down some logging
=> Various updates for refactorings/transport

eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java
that ignore the new InstanceInfo.instanceId field.
=> 1.x Improve backwards compatibility with legacy eureka-client,

eureka-client/src/main/java/com/netflix/discovery/shared/resolver/aws/ConfigClusterResolver.java, eureka-client/src/test/java/com/netflix/discovery/shared/resolver/aws/ConfigClusterResolverTest.java
=> Use getScheme() to compare against https.

eureka-core/src/main/java/com/netflix/eureka/registry/PeerAwareInstanceRegistryImpl.java
=> Sleep during syncUp only if necessary

eureka-core/src/main/java/com/netflix/eureka/aws/AwsBinderDelegate.java, eureka-core/src/main/java/com/netflix/eureka/aws/AwsBindingStrategy.java, eureka-core/src/main/java/com/netflix/eureka/aws/ElasticNetworkInterfaceBinder.java
Added binder for aws elastic network interfaces.
This is done creating an AWSBinder and modifying the delegate to properly choose using the new binder strategy
=> Added ENI aws binder

eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java, eureka-core/src/main/java/com/netflix/eureka/registry/PeerAwareInstanceRegistryImpl.java, eureka-core/src/main/java/com/netflix/eureka/util/MeasuredRate.java
=> Fix (harmless) NPE at server startup due to init order on a metrics counter

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java, eureka-core/src/main/java/com/netflix/eureka/cluster/PeerEurekaNodes.java, eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java, eureka-core/src/main/java/com/netflix/eureka/registry/PeerAwareInstanceRegistryImpl.java, eureka-core/src/main/java/com/netflix/eureka/registry/RemoteRegionRegistry.java, eureka-core/src/test/java/com/netflix/eureka/resources/ReplicationConcurrencyTest.java
=> Fixing a potential registration race condition as described in issue #802

eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/JerseyEurekaHttpClientFactory.java
=> Propagate systemSSL config for client all the way through

eureka-core/src/main/java/com/netflix/eureka/aws/EIPManager.java, eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java
Ref PR #811 
Fix for issue #802 
Making the fix default now that is has been tested in production.
=> Moving experimental replication fix to default

eureka-client/src/main/java/com/netflix/discovery/TimedSupervisorTask.java
Don't schedule TimeSupervisorTask if scheduler is shutting down
Additional logging in case that executor and scheduler are shutting down.
I notice this when shutting down Tomcat server:
```
ERROR c.n.discovery.TimedSupervisorTask - task supervisor rejected the task
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@29004f06 rejected from java.util.concurrent.ThreadPoolExecutor@2d3fcefe[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 17]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
at …
```
=> Don't schedule TimeSupervisorTask if scheduler is shutting down.

eureka-client-archaius2/src/main/java/com/netflix/discovery/EurekaArchaius2ClientConfig.java, eureka-client/src/main/java/com/netflix/discovery/DefaultEurekaClientConfig.java, eureka-client/src/main/java/com/netflix/discovery/PropertyBasedClientConfigConstants.java
Nothing much, just a typo fix
INITIAL_REGISTRATION_REPLCIATION_DELAY_KEY -> INITIAL_REGISTRATION_REPLICATION_DELAY_KEY
=> - fix minor typo in PropertyBasedClientConfigConstants.java

eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/EurekaJerseyClientImpl.java
The builder only allows SSL configuration through system settings, though it can be useful to operate the discovery client on a separate SSL context from the server/system level.  This exposes a method to supply an SSLContext object and use it in the "createCustomSslCM" method.
=> Allow for independent SSL context for EurekaJerseyClient

eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientHealthTest.java, eureka-core/src/main/java/com/netflix/eureka/resources/PeerReplicationResource.java, eureka-core/src/test/java/com/netflix/eureka/resources/PeerReplicationResourceTest.java
=> Add a guard to PR #934

build.gradle, eureka-client/build.gradle, eureka-client/src/main/java/com/netflix/appinfo/AbstractInstanceConfig.java, eureka-client/src/main/java/com/netflix/appinfo/AmazonInfo.java, eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java, eureka-client/src/main/java/com/netflix/discovery/AbstractAzToRegionMapper.java, eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java, eureka-client/src/main/java/com/netflix/discovery/TimedSupervisorTask.java, eureka-client/src/main/java/com/netflix/discovery/converters/EnumLookup.java, eureka-client/src/main/java/com/netflix/discovery/converters/EurekaJacksonCodec.java, eureka-client/src/main/java/com/netflix/discovery/converters/jackson/builder/StringInterningAmazonInfoBuilder.java, eureka-client/src/main/java/com/netflix/discovery/shared/Application.java, eureka-client/src/main/java/com/netflix/discovery/shared/Applications.java, eureka-client/src/main/java/com/netflix/discovery/util/DeserializerStringCache.java, eureka-client/src/main/java/com/netflix/discovery/util/EurekaEntityComparators.java, eureka-client/src/test/java/com/netflix/discovery/converters/EnumLookupTest.java, eureka-client/src/test/java/com/netflix/discovery/converters/EurekaJacksonCodecIntegrationTest.java, eureka-client/src/test/java/com/netflix/discovery/converters/EurekaJacksonCodecTest.java, eureka-client/src/test/java/com/netflix/discovery/shared/ApplicationsTest.java, eureka-core/src/main/java/com/netflix/eureka/registry/RemoteRegionRegistry.java
moved to Java 8
extensive changes to jackson deserialization to reduce heap usage
=>  memory tuning

eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerConfig.java, eureka-core/src/main/java/com/netflix/eureka/registry/RemoteRegionRegistry.java, eureka-core/src/main/java/com/netflix/eureka/registry/ResponseCacheImpl.java
Also updated some default server configs to do with connect and read timeouts to be more reasonable.
=> Fix a race condition in the server remoteRegionRegistry

eureka-core/src/main/java/com/netflix/eureka/resources/InstanceResource.java
Increase the catch exception code to ensure that when the exception occurs can be friendly to return to the client side
=> Increase the catch exception code

eureka-client/src/main/java/com/netflix/discovery/InstanceInfoReplicator.java
=> Avoid scheduling when DiscoveryClient.shutdown called

eureka-client/src/main/java/com/netflix/discovery/InstanceInfoReplicator.java
=> Verify if scheduler is active before submit new task

eureka-core/src/main/java/com/netflix/eureka/util/batcher/TaskExecutors.java
=> fix potential NPE for issue #1014

eureka-client/src/main/java/com/netflix/discovery/InstanceInfoReplicator.java
Fixes gh-1025.
(cherry-picked from master branch as the fork branch has been deleted)
=> Verify is scheduler is active before submit

eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java, eureka-client/src/main/java/com/netflix/discovery/converters/Converters.java, eureka-client/src/test/java/com/netflix/discovery/converters/EurekaCodecCompatibilityTest.java
further relax deser behaviour on overriddenstatus field to allow for both lower and camel case
=> change overriddenstatus field name in pojo to allow for better serialization compatibility

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
Remove magic number and replaced by `Status`
=> Tiny improve

eureka-client/src/main/java/com/netflix/discovery/internal/util/AmazonInfoUtils.java
Add User-Agent when requesting information from AWS Metadata service
=> Add User-Agent when requesting information from AWS Metadata service

eureka-client/src/main/java/com/netflix/discovery/TimedSupervisorTask.java, eureka-client/src/main/java/com/netflix/discovery/provider/DiscoveryJerseyProvider.java, eureka-client/src/main/java/com/netflix/discovery/shared/transport/decorator/RedirectingEurekaHttpClient.java
- Improve logging by linking cause to WebApplicationException
- Add attempt counter to TimeSupervisorTask to help identify situations where the supervisor has stalled
=> Improved logging

eureka-client-jersey2/build.gradle
Remove unused javax.mail dependency
=> Remove unused javax.mail dependency

eureka-client/src/main/java/com/netflix/discovery/shared/Applications.java
update the comment of  getRegisteredApplications(String appName)
=> update the comment

build.gradle, eureka-client/build.gradle, eureka-core/build.gradle
=> Update woodstox to 5.x

eureka-client/build.gradle, eureka-core/build.gradle
=> Upgrades xstream to 1.4.11.1

eureka-client/src/main/java/com/netflix/discovery/converters/EurekaJacksonCodec.java
=> move gain of lastDirtyTimestamp before gain of status to avoid race condition

eureka-core/src/main/java/com/netflix/eureka/util/StatusInfo.java
This is useful if a project has excluded Archaius 1 such as spring-cloud-netflix. This is a simple workaround.
=> Checks for existence of ConfigurationManager.

eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/JerseyApplicationClient.java
Modify iteration Map Mode。I think the performance through entrySet Iterate Map is better.
=> Modify iteration Map Mode

eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/JerseyApplicationClient.java
=> Revert "Improve map iteration in JerseyApplicationClient"

eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/JerseyApplicationClient.java
Modify iteration Map Mode.I think the performance through entrySet Iterate Map is better.
Thank you!
=> Modify iteration Map function

eureka-client/src/main/java/com/netflix/discovery/DefaultEurekaClientConfig.java
Bump default connection idle timeout to 45 seconds.
=> Bump default connection idle timeout

README.md
This build has been migrated to travis-ci.com as per their [recommendation](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom).
=> Update Build Status Location

eureka-client/build.gradle
Fix xstream security issue CVE-2021-39139
https://x-stream.github.io/security.html
=> Fix xstream security issue CVE-2021-39139

eureka-client/build.gradle, eureka-core/build.gradle
https://x-stream.github.io/changes.html
https://github.com/Netflix/eureka/issues/1455
=> xstream 1.4.19 (fixes a CVE)

eureka-client/build.gradle, eureka-core/build.gradle, eureka-core/src/main/java/com/netflix/eureka/cluster/ReplicationTaskProcessor.java, eureka-core/src/test/java/com/netflix/eureka/cluster/ReplicationTaskProcessorTest.java, eureka-core/src/test/java/com/netflix/eureka/cluster/TestableHttpReplicationClient.java
Ported from https://github.com/Netflix/eureka/pull/1503.
=> Fix handling null messages during timeout evaluation.

build.gradle, eureka-server-governator/build.gradle, eureka-server/build.gradle
Upgrade to a version without vulnerabilities. Issue raised in Spring Cloud Netflix: https://github.com/spring-cloud/spring-cloud-netflix/issues/4238.
=> Upgrade jettison to 1.5.4.

eureka-client/build.gradle
Related to  https://github.com/spring-cloud/spring-cloud-netflix/issues/4277.
=> Upgrade xstream to 1.4.20.

eureka-client/build.gradle, eureka-core/build.gradle
See https://github.com/spring-cloud/spring-cloud-netflix/issues/4398
=> Upgrade XStream to 1.4.21
