.gitignore
build.gradle
eureka2-metrics-spectator/build.gradle
eureka2-metrics-spectator/src/main/java/com/netflix/eureka2/metric/SpectatorEurekaMetrics.java
eureka2-metrics-spectator/src/test/java/com/netflix/eureka2/metric/SpectatorEurekaMetricsTest.java

+ use bintray snapshot repo by default, till we do first eureka2 RC release.

2.x Use interface base names as metrics class tag value.

---

eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java

InstanceInfo uses String.toUpperCase() without passing a Locale. This
is very dangerous as it relies on the default locale which might not
match the server's Locale. It is one of the APIs that are discouraged
for use, and it is better if it always passes a Locale.ROOT.

Don't use String.toUpperCase()

---

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java

The code checked if isInfoEnabled() but then called logger.debug().

Check for right logging level

---

eureka2-client/src/main/java/com/netflix/eureka2/client/interest/InterestHandlerImpl.java
eureka2-client/src/test/java/com/netflix/eureka2/client/interest/InterestHandlerTest.java
eureka2-core/src/main/java/com/netflix/eureka2/channel/AbstractClientChannel.java
eureka2-core/src/main/java/com/netflix/eureka2/registry/PreservableEurekaRegistry.java
eureka2-core/src/main/java/com/netflix/eureka2/registry/SourcedEurekaRegistry.java
eureka2-core/src/main/java/com/netflix/eureka2/registry/SourcedEurekaRegistryImpl.java
eureka2-read-server/src/main/java/com/netflix/eureka2/server/registry/EurekaReadServerRegistry.java
eureka2-test-utils/src/main/java/com/netflix/eureka2/channel/TestInterestChannel.java

- client interestChannel now evict older entries once new channel is available
- AbstractClientChannel properly handle connection lifecycle

2.x client fixes

---

build.gradle
eureka-core/build.gradle
eureka-server/build.gradle

Because of the transitive dependencies we had two servlet-api jar
versions in the dependency tree. Eureka depended directly on
version 2.4 that was properly marked as provided. This version was
however shadowed by the one from the transitive dependency (2.5),
and as it was not marked as provided nor excluded, it was added to
war file. That caused compatibility issue when running on tomcat 8.0.

1.x Exclude servlet-api jar from eureka.war

---

eureka-core/src/main/java/com/netflix/eureka/InstanceRegistry.java

This is bug fix for PR #412.
Require re-registration when instance status is UNKNOWN, after override removal.
This does not change the current behavior when new status is set as part of the DELETE request.

Require re-registration when instance status is UNKNOWN, after override removal.

---

eureka2-client/src/main/java/com/netflix/eureka2/client/interest/AbstractInterestClient.java
eureka2-client/src/main/java/com/netflix/eureka2/client/interest/EurekaInterestClientImpl.java
eureka2-core/src/main/java/com/netflix/eureka2/interests/FullRegistryInterest.java
eureka2-external-server/src/main/java/com/netflix/eureka2/server/EurekaClientProvider.java
eureka2-external-server/src/main/java/com/netflix/eureka2/server/RegistrationClientProvider.java
eureka2-external-server/src/main/java/com/netflix/eureka2/server/WriteClusterResolvers.java
eureka2-read-server/src/main/java/com/netflix/eureka2/server/EurekaReadServerModule.java
eureka2-read-server/src/main/java/com/netflix/eureka2/server/FullFetchInterestClientProvider.java
eureka2-read-server/src/main/java/com/netflix/eureka2/server/interest/FullFetchBatchingRegistry.java
eureka2-read-server/src/main/java/com/netflix/eureka2/server/interest/FullFetchInterestClient.java
eureka2-read-server/src/main/java/com/netflix/eureka2/server/registry/EurekaReadServerRegistry.java
eureka2-read-server/src/main/java/com/netflix/eureka2/server/service/EurekaReadServerSelfRegistrationService.java
eureka2-read-server/src/test/java/com/netflix/eureka2/server/interest/FullFetchInterestClientTest.java
eureka2-read-server/src/test/java/com/netflix/eureka2/server/registry/EurekaReadServerRegistryTest.java
eureka2-testkit/src/main/java/com/netflix/eureka2/testkit/embedded/server/EmbeddedReadServer.java

The custom client uses single subscription (fullRegistryFetch), and propagates properly channel level buffer markers to interest subscribers.

2.x Implement custom EurekaInterestClient for Eureka Read server.

---

eureka2-client/src/main/java/com/netflix/eureka2/client/channel/InterestChannelImpl.java
eureka2-client/src/main/java/com/netflix/eureka2/client/interest/EurekaInterestClientImpl.java
eureka2-core/src/main/java/com/netflix/eureka2/registry/NotifyingInstanceInfoHolder.java
eureka2-core/src/main/java/com/netflix/eureka2/registry/PreservableEurekaRegistry.java
eureka2-core/src/main/java/com/netflix/eureka2/registry/Source.java
eureka2-core/src/main/java/com/netflix/eureka2/registry/SourcedEurekaRegistry.java
eureka2-core/src/main/java/com/netflix/eureka2/registry/SourcedEurekaRegistryImpl.java
eureka2-core/src/test/java/com/netflix/eureka2/registry/NotifyingInstanceInfoHolderDataStoreTest.java
eureka2-core/src/test/java/com/netflix/eureka2/registry/NotifyingInstanceInfoHolderTest.java
eureka2-core/src/test/java/com/netflix/eureka2/registry/PreservableEurekaRegistryTest.java
eureka2-core/src/test/java/com/netflix/eureka2/registry/SourceTest.java
eureka2-read-server/src/main/java/com/netflix/eureka2/server/registry/EurekaReadServerRegistry.java

- updates for the same origin:name Sources replace each other regardless of source.id
- deletes only execute when origin:name:id equals for the sources

2.x Changes to MultiSourcedDataHolder implementation

---

eureka2-bridge/src/main/java/com/netflix/eureka2/server/channel/BridgeChannelImpl.java
eureka2-bridge/src/main/java/com/netflix/eureka2/server/service/BridgeService.java
eureka2-client/src/test/java/com/netflix/eureka2/client/interest/EurekaInterestClientImplTest.java
eureka2-core/src/main/java/com/netflix/eureka2/connection/RetryableConnectionFactory.java
eureka2-test-utils/src/main/java/com/netflix/eureka2/channel/TestSenderReplicationChannel.java
eureka2-write-server/src/main/java/com/netflix/eureka2/server/channel/ReceiverReplicationChannel.java
eureka2-write-server/src/main/java/com/netflix/eureka2/server/service/replication/ReplicationHandlerImpl.java

- handler should subscribe to lifecycle and operation with same subscriber for retries
- retryableChannelFactory merge internal channel op with lifecycle instead of independent subscribe

2.x Replication fix

---

build.gradle
eureka-client/build.gradle
eureka-core/build.gradle

The primary one that matters to me is ribbon. The older
version is still pulling in 'com.netflix.rxjava:rxjava-core'
which conflicts with classes in 'io.reactivex:rxjava'.
This change also changes the aws dependency to only pull
in the parts that are actually used by eureka client.

update dependency versions

---

eureka2-client/src/main/java/com/netflix/eureka2/client/interest/AbstractInterestClient.java
eureka2-client/src/main/java/com/netflix/eureka2/client/registration/EurekaRegistrationClientImpl.java
eureka2-client/src/test/java/com/netflix/eureka2/client/resolver/OcelliServerResolverTest.java
eureka2-server/src/main/java/com/netflix/eureka2/server/channel/InterestChannelImpl.java
eureka2-write-server/src/main/java/com/netflix/eureka2/server/service/replication/ReplicationHandlerImpl.java

- use concatMap instead of flatMap for sending interest and replication messages
- update channel retries to default at 1s instead of 500ms

2.x Use concatMap instead of flatMap for sending interest and replication messages

---

eureka2-client/src/main/java/com/netflix/eureka2/client/channel/InterestChannelImpl.java
eureka2-core/src/main/java/com/netflix/eureka2/transport/base/HeartBeatConnection.java
eureka2-core/src/test/java/com/netflix/eureka2/transport/base/HeartBeatConnectionTest.java
eureka2-server/src/main/java/com/netflix/eureka2/server/channel/InterestChannelImpl.java
eureka2-server/src/main/java/com/netflix/eureka2/server/transport/tcp/discovery/TcpDiscoveryServer.java
eureka2-write-server/src/main/java/com/netflix/eureka2/server/service/replication/ReplicationHandlerImpl.java

Also reverting interestChannel and SenderReplicationChannel send to flatmap instead of concatMap. Added TODOs to re-address these once we rework the interest pipeline to properly address backpressure (github issue #467)

2.x minor fixes

---

eureka2-client/src/main/java/com/netflix/eureka2/client/resolver/DnsResolverStep.java
eureka2-client/src/main/java/com/netflix/eureka2/client/resolver/OcelliServerResolver.java
eureka2-client/src/test/java/com/netflix/eureka2/client/resolver/DnsServerResolverTest.java
eureka2-core/src/main/java/com/netflix/eureka2/interests/host/DnsChangeNotificationSource.java
eureka2-core/src/main/java/com/netflix/eureka2/interests/host/DnsResolver.java

DnsResolver query dns on-demand per resolve() call instead of maintaining a background task to constantly poll dns.

2.x DnsResolver query dns on-demand per resolve()

---

eureka-client/src/main/java/com/netflix/discovery/TimedSupervisorTask.java
eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerConfig.java
eureka-core/src/main/java/com/netflix/eureka/EurekaServerConfig.java
eureka-core/src/main/java/com/netflix/eureka/RemoteRegionRegistry.java

Add thread pool level gauge for observing current thread usage level.

1.x Make TimedSupervisorTask thread pool configurable for remote region replication

---

eureka2-core/src/main/java/com/netflix/eureka2/registry/datacenter/AwsDataCenterInfoProvider.java
eureka2-ext/eureka2-eureka1-rest-api/src/main/java/com/netflix/eureka2/eureka1/rest/query/Eureka2FullFetchWithDeltaView.java
eureka2-ext/eureka2-eureka1-rest-api/src/main/java/com/netflix/eureka2/eureka1/rest/query/Eureka2RegistryViewCache.java
eureka2-ext/eureka2-eureka1-rest-api/src/main/java/com/netflix/eureka2/eureka1/rest/registry/RegistrationHandler.java
eureka2-ext/eureka2-eureka1-rest-api/src/test/java/com/netflix/eureka2/eureka1/rest/Eureka1QueryRequestHandlerTest.java
eureka2-ext/eureka2-eureka1-rest-api/src/test/java/com/netflix/eureka2/eureka1/rest/Eureka1RegistrationRequestHandlerTest.java
eureka2-ext/eureka2-eureka1-rest-api/src/test/java/com/netflix/eureka2/eureka1/rest/registry/Eureka1RegistryProxyImplTest.java
eureka2-ext/eureka2-eureka1-support/build.gradle
eureka2-ext/eureka2-eureka1-support/src/main/java/com/netflix/eureka2/eureka1/utils/Eureka1ModelConverters.java
eureka2-ext/eureka2-eureka1-support/src/main/java/com/netflix/eureka2/eureka1/utils/ServerListReader.java
eureka2-ext/eureka2-eureka1-support/src/test/java/com/netflix/eureka2/eureka1/utils/Eureka1ModelConvertersTest.java
eureka2-ext/eureka2-karyon-admin/src/main/java/netflix/adminresources/resources/Eureka2RegistryItemTypeAdapter.java
eureka2-testkit/src/main/java/com/netflix/eureka2/testkit/cli/EurekaCLI.java
eureka2-testkit/src/main/java/com/netflix/eureka2/testkit/cli/Session.java
eureka2-testkit/src/main/java/com/netflix/eureka2/testkit/cli/command/InterestCommand.java
gradle.properties
settings.gradle

Add eureka2-eureka1-support module to help bridge existing
Eureka1 clients to Eureka2 without adopting Eureka2 client API yet.

Add eureka2-eureka1-support module

---

eureka-client/src/main/java/com/netflix/appinfo/providers/EurekaConfigBasedInstanceInfoProvider.java
eureka-client/src/test/java/com/netflix/discovery/converters/InstanceInfoGenerator.java

bug fix: Re-adding @LazySingleton to EurekaInstanceInfoProvider to ensure InstanceInfo singleton for injection into DiscoveryClient and ApplicationInfoManager.

singleton scoping EurekaConfigBasedInstanceInfoProvider

---

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientCloseJerseyThreadTest.java

When reloading or shutting down the context in Tomcat 8 we get a warning that there was a thread created but not cleaned up:
```
WARNING: The web application [example] appears to have started a thread named [Eureka-JerseyClient-Conn-Cleaner2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809) …
```

Destroying jersey cleaner thread on DiscoveryClient shutdown

---

eureka2-integration/src/test/java/com/netflix/eureka2/integration/startup/AbstractStartupAndShutdownIntegrationTest.java
eureka2-integration/src/test/resources/bridge-server-startupAndShutdown.properties
eureka2-integration/src/test/resources/dashboard-server-startupAndShutdown.properties
eureka2-integration/src/test/resources/read-server-startupAndShutdown.properties
eureka2-integration/src/test/resources/write-server-startupAndShutdown.properties
eureka2-server/src/main/java/com/netflix/eureka2/server/AbstractEurekaServer.java
eureka2-server/src/main/java/com/netflix/eureka2/server/health/HealthStatusProviderRegistry.java
eureka2-server/src/test/java/com/netflix/eureka2/server/health/HealthStatusProviderRegistryTest.java

Dashboard/bridge do not provide yet any health check provider, so observable
stream of server status never emitted any value. In this change, if there are no
providers bound, a default one is registered returning always Status.UP.

2.x Fix dashboard/bridge health check. Add integration test to verify that.

---

eureka-core/build.gradle
eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerConfig.java
eureka-core/src/main/java/com/netflix/eureka/EurekaServerConfig.java
eureka-core/src/main/java/com/netflix/eureka/util/AwsAsgUtil.java

The motivation of this patch is to make Eureka capable of knowing the state of auto scaling groups even if they are from microservices running in accounts other than the one where Eureka is running.
In that case, it will do a a cross-account assume role to get permission to describe the ASGs.
[Here](http://docs.aws.amazon.com/IAM/latest/UserGuide/roles-walkthrough-crossacct.html ) is a walkthrough from Amazon that explains how to setup the cross-account IAM role delegation: 
The role must be called `ListAutoScalingGroups` and the policy must be like this:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Action": [
"autoscaling:DescribeAutoScalingGroups"
],
"Effect": "Allow",
"Resource": "*"
}
]
} 
```

Cross account describe ASGs

---

eureka2-client/src/main/java/com/netflix/eureka2/client/channel/InterestChannelImpl.java
eureka2-client/src/test/java/com/netflix/eureka2/client/channel/InterestChannelImplTest.java
eureka2-core/src/main/java/com/netflix/eureka2/interests/Index.java
eureka2-core/src/main/java/com/netflix/eureka2/interests/IndexRegistry.java
eureka2-core/src/main/java/com/netflix/eureka2/interests/InstanceInfoInitStateHolder.java
eureka2-core/src/main/java/com/netflix/eureka2/interests/MultipleInterests.java
eureka2-core/src/main/java/com/netflix/eureka2/registry/SourcedEurekaRegistryImpl.java
eureka2-integration/src/test/java/com/netflix/eureka2/integration/EurekaClientIntegrationTest.java
eureka2-integration/src/test/java/com/netflix/eureka2/integration/IntegrationTestClassSetup.java
eureka2-integration/src/test/java/com/netflix/eureka2/integration/ReadServerIntegrationTest.java
eureka2-integration/src/test/java/com/netflix/eureka2/integration/ReadWriteClusterIntegrationTest.java
eureka2-integration/src/test/java/com/netflix/eureka2/integration/WriteClusterIntegrationTest.java
eureka2-integration/src/test/java/com/netflix/eureka2/integration/WriteServerIntegrationTest.java
eureka2-integration/src/test/java/com/netflix/eureka2/integration/batching/IndexBatchMergeIntegrationTest.java
eureka2-integration/src/test/java/com/netflix/eureka2/integration/examples/SimpleAppIntegrationTest.java
eureka2-integration/src/test/java/com/netflix/eureka2/integration/mixedcodec/AbstractMixedCodecTest.java
eureka2-integration/src/test/java/com/netflix/eureka2/integration/random/AbstractRandomLifecycleTest.java
eureka2-test-utils/src/main/java/com/netflix/eureka2/rx/ExtTestSubscriber.java

- Clean up extra use of a subject in the initStateHolder
- Adding temporary fix for client side batching issue (too eagerly emit BufferMarker when local cache is empty but data is transmitted from server side).

2.x Refactorings/reactive registry

---

eureka-client/src/main/java/com/netflix/discovery/CacheRefreshedEvent.java
eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/main/java/com/netflix/discovery/DiscoveryEvent.java
eureka-client/src/main/java/com/netflix/discovery/StatusChangeEvent.java

The objective is to capture "cache refreshed" events. A few comments (following discussion in https://github.com/Netflix/eureka/issues/545):
1/ Added protected methods invoked when remote status is changed and cache is refreshed. They  are currently responsible to fire the appropriate event to the EventBus if one is available.
They are intentionally made protected so subclasses of the `DiscoveryClient` can override them if they need more advanced behaviour like:
- implement the Observer pattern and invoke registered listeners/observers
- compute actual changes when cache is refreshed
- etc
2/ I could create a `CacheRefreshedEvent` similar to the existing `StatusChangedEvent` and fire it every time the cache is refreshed. However, I'm not sure about the implications this additional event …

Capture "CacheRefreshed" event

---

build.gradle
eureka2-bridge/build.gradle
eureka2-bridge/src/main/java/com/netflix/eureka2/server/EurekaBridgeServerConfigurationModule.java
eureka2-bridge/src/main/java/com/netflix/eureka2/server/EurekaBridgeServerRunner.java
eureka2-dashboard/build.gradle
eureka2-dashboard/src/main/java/com/netflix/eureka2/EurekaDashboardConfigurationModule.java
eureka2-dashboard/src/main/java/com/netflix/eureka2/EurekaDashboardRunner.java
eureka2-ext/eureka2-kafka/build.gradle
eureka2-ext/eureka2-kafka/src/main/java/com/netflix/eureka2/server/audit/kafka/KafkaAuditService.java
eureka2-ext/eureka2-kafka/src/main/java/com/netflix/eureka2/server/audit/kafka/KafkaAuditServiceModule.java
eureka2-ext/eureka2-kafka/src/main/java/com/netflix/eureka2/server/audit/kafka/KafkaServersProvider.java
eureka2-ext/eureka2-kafka/src/main/java/com/netflix/eureka2/server/audit/kafka/config/KafkaAuditServiceConfig.java
eureka2-ext/eureka2-kafka/src/main/java/com/netflix/eureka2/server/audit/kafka/config/bean/KafkaAuditServiceConfigBean.java
eureka2-ext/eureka2-kafka/src/test/java/com/netflix/eureka2/server/audit/kafka/KafkaAuditServiceTest.java
eureka2-ext/eureka2-karyon-admin/build.gradle
eureka2-ext/eureka2-karyon-admin/src/main/java/netflix/adminresources/resources/eureka/registry/InstanceRegistryCache.java
eureka2-read-server/build.gradle
eureka2-read-server/src/main/java/com/netflix/eureka2/server/EurekaReadServerConfigurationModule.java
eureka2-read-server/src/main/java/com/netflix/eureka2/server/EurekaReadServerRunner.java
eureka2-server/build.gradle
eureka2-server/src/main/java/com/netflix/eureka2/server/AbstractEurekaServer.java
eureka2-server/src/main/java/com/netflix/eureka2/server/module/ServerConfigurationModule.java
eureka2-testkit/build.gradle
eureka2-write-server/build.gradle
eureka2-write-server/src/main/java/com/netflix/eureka2/server/EurekaWriteServerConfigurationModule.java
eureka2-write-server/src/main/java/com/netflix/eureka2/server/EurekaWriteServerRunner.java
gradle.properties

- use karyon3 for consolidated config loading across modules and extModules
- switch kafka dep to kafka-clients and other dependency clean ups
- update eureka2-kafka to use latest archaius for config loading
- update gradle runners
- change admin eureka2 view to read directly from registry

2.x various fixes

---

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/main/java/com/netflix/discovery/DiscoveryManager.java

So we can do things like add Authorization headers and authenticate those on the Eureka Server

Add the ability to use additional Jersey ClientFilters in the DiscoveryClient

---

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java

This triggers Archaius static initialization, which is not necessary here.

Remove unused reference to DynamicPropertyFactory

---

eureka-core/src/main/java/com/netflix/eureka/util/EurekaMonitors.java

Fix for https://github.com/Netflix/eureka/issues/638

Properly unregister Servo monitors on shutdown

---

eureka-client/src/main/java/com/netflix/discovery/DefaultEurekaClientConfig.java

Hello,
I've seen that the eureka.region property in DefaultEurekaClientConfig.class it's not tied to the namespace, and when using a different namespace there is the need to hardcode this property.
Regards,
Jaume

EurekaNameSpace not used in eureka.region

---

eureka-core/src/main/java/com/netflix/eureka/resources/StatusResource.java

We see this when we're running single nodes, more of a support issue than a problem. We keep getting people asking about it.
```
2015-10-02 11:35:16.760 ERROR 3755 --- [nio-8761-exec-4] c.n.eureka.resources.StatusResource      : Could not determine if the replica is available
java.lang.NullPointerException: null
at com.netflix.eureka.resources.StatusResource.isReplicaAvailable(StatusResource.java:87) [5da40e7f691eb25c4b46f56115ec929776e850fc-eureka-core-1.2.5.jar:1.2.5]
at com.netflix.eureka.resources.StatusResource.getStatusInfo(StatusResource.java:67) [5da40e7f691eb25c4b46f56115ec929776e850fc-eureka-core-1.2.5.jar:1.2.5]
at org.springframework.cloud.netflix.eureka.server.EurekaController.status(EurekaController.java:68) [spring-cloud-netflix-eureka-server-1.1.0.BUILD-SNAPSHOT.jar!/:1.1.0 …
```

Fix NPE in StatusResource.isReplicaAvailable

---

eureka-client-archaius2/src/main/java/com/netflix/discovery/shared/transport/EurekaArchaius2TransportConfig.java
eureka-client/src/main/java/com/netflix/discovery/EurekaClientNames.java
eureka-client/src/main/java/com/netflix/discovery/shared/resolver/aws/EurekaHttpResolver.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/DefaultEurekaTransportConfig.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaHttpClients.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaTransportConfig.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/decorator/RetryableEurekaHttpClient.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/decorator/SessionedEurekaHttpClient.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/AbstractJerseyEurekaHttpClient.java
eureka-client/src/test/java/com/netflix/discovery/shared/transport/EurekaHttpClientsTest.java
eureka-client/src/test/java/com/netflix/discovery/shared/transport/decorator/RetryableEurekaHttpClientTest.java
eureka-client/src/test/java/com/netflix/discovery/shared/transport/decorator/SessionedEurekaHttpClientTest.java
eureka-core/src/main/java/com/netflix/eureka/Names.java
eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java
eureka-core/src/main/java/com/netflix/eureka/registry/PeerAwareInstanceRegistryImpl.java
eureka-core/src/main/java/com/netflix/eureka/registry/RemoteRegionRegistry.java
eureka-core/src/main/java/com/netflix/eureka/transport/EurekaServerHttpClients.java

- add config to define quarantine clear condition
- better metrics and logging
- adding jitter to sessionedClient's session duration

1.x new transport enhancements

---

eureka-client-archaius2/src/main/java/com/netflix/discovery/Ec2EurekaArchaius2InstanceConfig.java
eureka-client-archaius2/src/main/java/com/netflix/discovery/EurekaArchaius2InstanceConfig.java
eureka-client/src/main/java/com/netflix/appinfo/AmazonInfo.java
eureka-client/src/main/java/com/netflix/appinfo/ApplicationInfoManager.java
eureka-client/src/main/java/com/netflix/appinfo/CloudInstanceConfig.java
eureka-client/src/main/java/com/netflix/appinfo/EurekaInstanceConfig.java
eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java
eureka-client/src/main/java/com/netflix/appinfo/PropertiesInstanceConfig.java
eureka-client/src/main/java/com/netflix/appinfo/providers/EurekaConfigBasedInstanceInfoProvider.java
eureka-client/src/main/java/com/netflix/discovery/EurekaClientConfig.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaTransportConfig.java
eureka-client/src/test/java/com/netflix/appinfo/ApplicationInfoManagerTest.java
eureka-client/src/test/java/com/netflix/appinfo/CloudInstanceConfigTest.java

Adding ability to define resolution order of the local InstanceInfo's "default" network address based on data available in AmazonInfo.

1.x Client InstanceInfo default address resolution

---

eureka-client/build.gradle

This effectively removes eureka-client's only transitive dependency on LGPL code.

Upgrade netflix-eventbus to purge the transitive dependency on findbugs

---

eureka-client/src/main/java/com/netflix/appinfo/ApplicationInfoManager.java
eureka-client/src/main/java/com/netflix/appinfo/CloudInstanceConfig.java
eureka-client/src/main/java/com/netflix/appinfo/providers/EurekaConfigBasedInstanceInfoProvider.java
eureka-client/src/test/java/com/netflix/appinfo/ApplicationInfoManagerTest.java
eureka-client/src/test/java/com/netflix/appinfo/CloudInstanceConfigTest.java

AWS meta data updates were ignored, which for Discovery servers themselves resulted in an infinite loop of EIP binding, and registry clear/upload sequences. This in turn caused massive expiries, and large network traffic.

1.x Fix AWS meta data refresh

---

eureka-client/src/main/java/com/netflix/appinfo/AmazonInfo.java
eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java
eureka-core/src/main/java/com/netflix/eureka/resources/ApplicationResource.java
eureka-core/src/test/java/com/netflix/eureka/resources/ApplicationResourceTest.java

- Moving data backfill of AmazonInfo from InstanceInfo ctor to Resource that handles registration
- Adding an option to return 400 to such registration requests instead of backfill data

Handle registration with bad data in DataCenterInfo

---

README.md
build.gradle
eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/test/java/com/netflix/discovery/shared/transport/EurekaHttpClientsTest.java
eureka-core/src/main/java/com/netflix/eureka/transport/JerseyRemoteRegionClientFactory.java

Spring Cloud Netflix is still java7 compatible.
When using java7 to build, the following error occurs because servo is java8 only.
java.lang.UnsupportedClassVersionError: com/netflix/servo/monitor/Monitors
at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:126)
at com.netflix.discovery.BackUpRegistryTest.setUp(BackUpRegistryTest.java:71)
Spring Cloud Netflix still uses the java7 servo.
Building with java8 and targeting java7 still works and maintains the required compatibility.
@twicksell

Move back to java7 compatibility.

---

eureka-client-archaius2/src/main/java/com/netflix/discovery/shared/transport/EurekaArchaius2TransportConfig.java
eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/main/java/com/netflix/discovery/shared/Applications.java
eureka-client/src/main/java/com/netflix/discovery/shared/resolver/AsyncResolver.java
eureka-client/src/main/java/com/netflix/discovery/shared/resolver/DefaultEndpoint.java
eureka-client/src/main/java/com/netflix/discovery/shared/resolver/EurekaEndpoint.java
eureka-client/src/main/java/com/netflix/discovery/shared/resolver/LegacyClusterResolver.java
eureka-client/src/main/java/com/netflix/discovery/shared/resolver/ResolverUtils.java
eureka-client/src/main/java/com/netflix/discovery/shared/resolver/aws/ApplicationsResolver.java
eureka-client/src/main/java/com/netflix/discovery/shared/resolver/aws/EurekaHttpResolver.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/DefaultEurekaTransportConfig.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaHttpClients.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaTransportConfig.java
eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientRedirectTest.java
eureka-client/src/test/java/com/netflix/discovery/shared/resolver/aws/ApplicationsResolverTest.java
eureka-client/src/test/java/com/netflix/discovery/shared/resolver/aws/EurekaHttpResolverTest.java
eureka-client/src/test/java/com/netflix/discovery/shared/resolver/aws/TestEurekaHttpResolver.java
eureka-client/src/test/java/com/netflix/discovery/shared/transport/EurekaHttpClientsTest.java
eureka-core/src/test/java/com/netflix/eureka/cluster/JerseyReplicationClientTest.java

Two features for multi-account, multi vpc type support:
- an option for (all) resolvers to use hostnames or ipAddresses for resolution
- an option to bootstrap with a composite strategy, where the bootstrap resolver prefers to load data from local registry, else attempts to make a remote get vips call for write servers. The remote call will make a dns/config look up for target hosts.

1.x Add composite strategy bootstrap resolver 

---

eureka-client/src/main/java/com/netflix/discovery/provider/DiscoveryJerseyProvider.java
eureka-client/src/test/java/com/netflix/discovery/provider/DiscoveryJerseyProviderTest.java

This PR (compared to the previouse, undone one #739) checks for entity
types and is applied only to eureka specific data structures.

Fix for issue #702 (handle charset provided in Content-Type header)

---

eureka-client/src/main/java/com/netflix/discovery/shared/resolver/DefaultEndpoint.java
eureka-client/src/test/java/com/netflix/discovery/shared/resolver/aws/ConfigClusterResolverTest.java

Fixes a problem communicating with an eureka server that is running on port 80 or 443 (such as the case in cloud foundry). serviceUrl looked like this http://eurekahost:-1
I can confirm this works on a local build.
See https://github.com/spring-cloud/spring-cloud-netflix/issues/840 for the original issue.

Only append port to serviceUrl if port >= 0

---

eureka-core/src/main/java/com/netflix/eureka/aws/EIPManager.java

Instead, throw exception
Reason: DescribeAddressRequest with null public ip returns list of all public address
If instance is not associated with one eip, Eureka will dissociate first ip on list which does not belong to the instance

1.x EIPManager: if instance is not associated with one EIP, do not try to unbind

---

eureka-client/src/main/java/com/netflix/appinfo/AmazonInfo.java
eureka-client/src/main/java/com/netflix/appinfo/ApplicationInfoManager.java
eureka-client/src/main/java/com/netflix/appinfo/CloudInstanceConfig.java
eureka-client/src/main/java/com/netflix/appinfo/providers/EurekaConfigBasedInstanceInfoProvider.java
eureka-client/src/test/java/com/netflix/appinfo/CloudInstanceConfigTest.java

Add fail fast option to AmazonInfo init (esp at bootstrap time) so that running with VPN will not unncecessarily cause long hang times waiting on each key's ReadTimeout.

Add fail fast option to AmazonInfo init

---

eureka-client/src/main/java/com/netflix/discovery/InstanceInfoReplicator.java
eureka-client/src/test/java/com/netflix/discovery/InstanceInfoReplicatorTest.java

When performing an on demand status update within the InstanceInfoReplicator start's initial delay the originally scheduled task is not cancelled which results in two scheduled tasks being executed for the life of the process.

Handle on demand update within InstanceInfoReplicator initial delay

---

eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaClientFactoryBuilder.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/JerseyEurekaHttpClientFactory.java

This commit is related to issue [https://github.com/spring-cloud/spring-cloud-netflix/issues/729](https://github.com/spring-cloud/spring-cloud-netflix/issues/729).
When overriding the connectionIdleTimeout value, it was erroneously using a seconds value, although default value is in milliseconds.

! Fix erroneous connectionIdleTimeout value

---

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/main/java/com/netflix/discovery/InternalEurekaStatusModule.java
eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientOptionalArgsTest.java

Made the changes to prefer the javax.inject Provider over the guice Provider where possible. The remaining usages of the guice provider are blocked by https://github.com/google/guice/pull/926.

Prefer javax.inject Provider over guice Provider for #807

---

eureka-core/src/main/java/com/netflix/eureka/aws/EIPManager.java

See issue #818 -
In a private application with no elastic IPs exceptions will be thrown when there are no URLs containing "ec2-".  With this modification, the exception will not be thrown and the rest of the process will simply not bind to any EIPs.

Check the sub-string index value before trying to sub-string on it.

---

eureka-core/src/main/java/com/netflix/eureka/cluster/PeerEurekaNodes.java
eureka-core/src/main/java/com/netflix/eureka/util/StatusUtil.java

When configuring the `eureka.serviceUrl.default` with IP addresses the comparisons performed in `PeerEurekaNodes` and `StatusUtil` prevent the instances from recognizing themselves and therefore never report themselves as available.
As discussed on #821 (https://github.com/Netflix/eureka/pull/821#issuecomment-237416131) follow PR.

Support eureka servers configured with IP addresses

---

eureka-core/src/main/java/com/netflix/eureka/util/StatusInfo.java
eureka-core/src/main/java/com/netflix/eureka/util/StatusUtil.java

Add a builder method and check that instanceInfo is not null in build().
Found this in a test where the static singleton was null :-(

Remove use of deprecated static accessor.

---

eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerConfig.java
eureka-core/src/main/java/com/netflix/eureka/EurekaServerConfig.java
eureka-core/src/main/java/com/netflix/eureka/cluster/PeerEurekaNodes.java
eureka-core/src/main/java/com/netflix/eureka/util/StatusUtil.java
eureka-core/src/test/java/com/netflix/eureka/util/StatusUtilTest.java

When one of the replicas is down the eureka server status should reflect that in the healthy flag on `StatusInfo` and `/eureka/v2/status` endpoint.

Support healthy status on server StatusInfo

---

eureka-client/src/main/java/com/netflix/appinfo/providers/CloudInstanceConfigProvider.java
eureka-client/src/main/java/com/netflix/appinfo/providers/EurekaConfigBasedInstanceInfoProvider.java
eureka-client/src/main/java/com/netflix/appinfo/providers/MyDataCenterInstanceConfigProvider.java
eureka-client/src/main/java/com/netflix/discovery/providers/DefaultEurekaClientConfigProvider.java

Follow up to #808 now that guice has been released and pulled in.

Convert all remaining guice provider references to javax

---

eureka-core/src/main/java/com/netflix/eureka/util/StatusInfo.java

f40f54a03d135379845aeb8c060b4f768fe7e7b5 made instanceInfo a required field to be set, but an assignment was still happening from `ApplicationInfoManager.getInstance().getInfo()` overwriting assigned field.

Remove assignment of instanceInfo from static instance.

---

eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/EurekaJerseyClientImpl.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/SSLSocketFactoryAdapter.java

Use Apache HttpClient 4.3+ SSL handling which supports SNI, and
adapt it to the deprecated pre 4.3 API.
Fixes #873

Support HTTPS requests to servers that use multiple certificates

---

eureka-client/src/main/java/com/netflix/discovery/shared/resolver/LegacyClusterResolver.java
eureka-client/src/main/java/com/netflix/discovery/shared/resolver/aws/ConfigClusterResolver.java

We get a lot of these log messages in our logfiles. We can't see which URL is causing the log message, as the placeholder {} is missing in the text. This pull request fixes this.

Fixed missing url in log output

---

eureka-client-archaius2/build.gradle
eureka-client-jersey2/build.gradle
eureka-client/build.gradle
eureka-core/build.gradle

Governator was scoped as a compile dependency of eureka-core incorrectly. A few other modules needed it for testing. This fixes consumers from pulling in this dependency transitively when it is not used.

Scope governator dependencies to reflect actual usage

---

README.md

There's a space in between the brackets and parentheses in the readme, which causes the links to not render properly. I've removed the space so the links look like links now.

Fix link rendering in README.md

---

eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java

remoteRegionUrlsWithName can never null, so change null check condition
According to EurekaServerConfig.java's remoteRegionUrlsWithName comment
Empty map if no remote region url is defined.
Now, Always running
https://github.com/Netflix/eureka/blob/4f24d9dcf90713b421f6c092fa63e707cbf74df3/eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java#L138-L151

Improving conditional statement for map

---

eureka-core/src/main/java/com/netflix/eureka/resources/PeerReplicationResource.java
eureka-core/src/test/java/com/netflix/eureka/resources/PeerReplicationResourceTest.java

Add the InstanceInfo to the response in case of 409 status code

---

build.gradle
eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java
eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java
eureka-core/src/main/java/com/netflix/eureka/resources/ApplicationResource.java
eureka-core/src/test/java/com/netflix/eureka/AbstractTester.java
eureka-core/src/test/java/com/netflix/eureka/registry/InstanceRegistryTest.java
eureka-core/src/test/java/com/netflix/eureka/resources/ApplicationResourceTest.java

Setting and deleting the override status on an eureka server has a regression due to the `lastDirtyTimestamp` being updated by the server in response to the set and delete, which can in turn lead to client update/registers potentially being ignored due to the timestamp being ahead on the server compared to client local.

Fix Override Status Regression

---

build.gradle
eureka-client-jersey2/src/main/java/com/netflix/discovery/shared/transport/jersey2/Jersey2ApplicationClientFactory.java
eureka-client-jersey2/src/main/java/com/netflix/discovery/shared/transport/jersey2/Jersey2TransportClientFactories.java
eureka-client/src/main/java/com/netflix/discovery/AbstractDiscoveryClientOptionalArgs.java
eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaClientFactoryBuilder.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/EurekaJerseyClientImpl.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/Jersey1TransportClientFactories.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/JerseyEurekaHttpClientFactory.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/SSLSocketFactoryAdapter.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/TransportClientFactories.java
eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java

Implementation of #816 
Supports configuration of custom SSLContext/HostnameVerifier for jersey1/jersey2 implementations.

Support configuration of custom SSLContext/HostnameVerifier

---

eureka-client/src/main/java/com/netflix/discovery/InstanceInfoReplicator.java

Based off code cleanup comments for pull #974, this should fix #973.
`awaitTermination` should block until the  DOWN replication thread is completed before finishing shutdown/registration.  This should prevent race conditions between registration:DOWN and de-register.

Avoid scheduling when DiscoveryClient.shutdown called (fix for #973)

---

eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java
eureka-core/src/main/java/com/netflix/eureka/resources/InstancesResource.java

Use `list.isEmpty ()` instead of `list.size>0` to make it more elegant.

Use a more elegant way to judge

---

eureka-core/src/main/java/com/netflix/eureka/cluster/ReplicationTaskProcessor.java
eureka-core/src/test/java/com/netflix/eureka/cluster/ReplicationTaskProcessorTest.java
eureka-core/src/test/java/com/netflix/eureka/cluster/TestableHttpReplicationClient.java

when the instance become more then 3k,the batch replicated operation become easier to timeout.
because the replication request sender will retry the replication soon,it leads to a flood.
When it's happend,it appears to some eureka node ocupied 100% CPU and stucked.
This commit will help reduce the sympton,and write a clear log message to help debug.
By the way , i suggest to allow user to config the Congestion and TransientError retry delay time

prevent replication flood caused by socket read time out leads to some node CPU 100%

---

eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/JerseyEurekaHttpClientFactory.java

Eureka proxy settings is not working because of EurekaJerseyClientBuilder instance have no chance to set proxy settings during it's lifecycle.
related issue: #1056

bugfixing: Eureka Proxy Setting is not working

---

eureka-client/src/main/java/com/netflix/discovery/endpoint/DnsResolver.java

fix #1053 
Remove the opening and closing quotes when the TXT dns record as format:
> "host1 host2 host3"
to compatible with aws route53 format:
>"host1" "host2" "host3"
(this format will remove quotes before the return of call dirContext.getAttributes(...))

update: compatible txt value format: "host1 host2 host3"

---

eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerContext.java
eureka-core/src/main/java/com/netflix/eureka/aws/AwsBinderDelegate.java
eureka-core/src/main/java/com/netflix/eureka/aws/EIPManager.java
eureka-core/src/main/java/com/netflix/eureka/aws/ElasticNetworkInterfaceBinder.java
eureka-core/src/main/java/com/netflix/eureka/aws/Route53Binder.java

975-Remove-checked-exceptions-from-@PostConstruct-methods

---

eureka-client/src/main/java/com/netflix/discovery/endpoint/EndpointUtils.java

When set `shouldUseDns` as true with null `eurekaServer.context`, `EndpointUtils#getServiceUrlsFromDNS` appends "null" string to service url postfix.
e.g. http://ec2-10-0-0-1.ap-northeast-2.compute.amazonaws.com/null/
Fixed this.

Prevent "null" url server url prefix

---

eureka-core/src/main/java/com/netflix/eureka/registry/PeerAwareInstanceRegistryImpl.java
eureka-core/src/test/java/com/netflix/eureka/AbstractTester.java
eureka-core/src/test/java/com/netflix/eureka/mock/MockRemoteEurekaServer.java
eureka-core/src/test/java/com/netflix/eureka/registry/InstanceRegistryTest.java
eureka-core/src/test/java/com/netflix/eureka/registry/TimeConsumingInstanceRegistryTest.java
eureka-core/src/test/java/com/netflix/eureka/test/async/executor/AsyncExecutorException.java
eureka-core/src/test/java/com/netflix/eureka/test/async/executor/AsyncResult.java
eureka-core/src/test/java/com/netflix/eureka/test/async/executor/AsyncSequentialExecutor.java
eureka-core/src/test/java/com/netflix/eureka/test/async/executor/Backoff.java
eureka-core/src/test/java/com/netflix/eureka/test/async/executor/ConcreteAsyncResult.java
eureka-core/src/test/java/com/netflix/eureka/test/async/executor/SequentialEvents.java
eureka-core/src/test/java/com/netflix/eureka/test/async/executor/SingleEvent.java

Fix the inconsistency logic in method `updateRenewalThreshold()`. Because it does not reflect the expected intention based on the comment. 
`updateRenewalThreshold` will be qualified to run if renewal count * 2 is bigger than 
```
serverConfig.getRenewalPercentThreshold() * expectedNumberOfRenewsPerMin
```
NOT
```
serverConfig.getRenewalPercentThreshold() * numberOfRenewsPerMinThreshold
```

Fix the inconsistency logic in method updateRenewalThreshold(). 

---

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/test/java/com/netflix/discovery/BaseDiscoveryClientTester.java
eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientHealthTest.java

Some clients try to register their health checks and fail since there is possibility to rewrite healthcheck handler by default one.
Root cause:
after not thread safe null check DiscoveryClient will register default healthcheck handler even if during creation of that, custom one will be provided.
Resolution summary:
wrap healthcheck handler in AtomicReference and set default implementation only if reference still contain null.
Example is spring-cloud-netflix project and https://github.com/spring-cloud/spring-cloud-netflix/issues/2490 issue.

Concurrent register of custom healthcheck handler in DiscoveryClient

---

eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerConfig.java
eureka-core/src/main/java/com/netflix/eureka/EurekaServerConfig.java
eureka-core/src/main/java/com/netflix/eureka/registry/ResponseCacheImpl.java

Hi @qiangdavidliu 
When `ResponseCacheImpl#readWriteCacheMap` init, it use hardcode to make initial capacity, so I add a parameter which can let customer decide the initial capacity.
Please check it.
Thanks : )

Cache capacity configurable

---

eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerConfig.java
eureka-core/src/main/java/com/netflix/eureka/EurekaServerConfig.java
eureka-core/src/main/java/com/netflix/eureka/cluster/PeerEurekaNodes.java

...to specify URL Eureka should treat as its own (for cases when each Eureka node is behind LB and does not simply check replica URLs against own IP/host)

EUREKA-1087 Add config parameter eureka.myUrl

---

eureka-server/src/main/resources/eureka-client.properties

The eureka server internal eureka-client need to be configured to get instances for all statuses, not just UP. This is necessary to properly calculate the correct self preservation threshold. See issue https://github.com/Netflix/eureka/issues/1127 for a discussion.

update default server's eureka-client property

---

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java

Tweak the staleness guages to return 0 for when the client is shut down or when refreshes are not enabled.  Otherwise the metric can be misleading by incorrectly making it appear that refreshes are not working.

Tweak Staleness metrics

---

eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java
eureka-client/src/test/java/com/netflix/discovery/shared/ApplicationsTest.java

Application(class) can get simple information by @Override the toString().
-> toString() in Application.java
@Override
public String toString() {
return "Application [name=" + name + ", isDirty=" + isDirty
+ ", instances=" + instances + ", shuffledInstances="
+ shuffledInstances + ", instancesMap=" + instancesMap + "]";
}
It is simple to use some information immediately.
But What is more necessary is the information in InstanceInfo(class)?
InstanceInfo provides a detailed information about the eureka client.
InstanceInfo provides a getter, but it has about 30 member variables.
So it seems necessary to provide the overriden toString() of InstanceInfo

  Add @Override toString() in InstanceInfo

---

eureka-core/src/main/java/com/netflix/eureka/aws/EIPManager.java
eureka-core/src/test/java/com/netflix/eureka/aws/EIPManagerTest.java

It looks like a -1 was used when it should be comparing against 3. Based on line 353, beginIndex will always be larger than -1, but it will be 3 if there is no "ec2-" in the URL.
This is for issue #1134 which I reported earlier this morning.

eureka-1134: fix for StringIndexOutOfBoundsException

---

eureka-client-archaius2/src/main/java/com/netflix/discovery/guice/InternalEurekaClientModule.java
eureka-client-jersey2/src/main/java/com/netflix/discovery/guice/Jersey2EurekaModule.java
eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/main/java/com/netflix/discovery/guice/EurekaModule.java
eureka-client/src/main/java/com/netflix/discovery/shared/resolver/EndpointRandomizer.java
eureka-client/src/main/java/com/netflix/discovery/shared/resolver/LegacyClusterResolver.java
eureka-client/src/main/java/com/netflix/discovery/shared/resolver/aws/ZoneAffinityClusterResolver.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaHttpClients.java
eureka-client/src/test/java/com/netflix/discovery/BackUpRegistryTest.java
eureka-client/src/test/java/com/netflix/discovery/EurekaClientLifecycleTest.java
eureka-client/src/test/java/com/netflix/discovery/shared/resolver/aws/ZoneAffinityClusterResolverTest.java
eureka-client/src/test/java/com/netflix/discovery/shared/transport/EurekaHttpClientsTest.java

This is another attempt to fix #1149. This time tried to take comments from #1151 into account.
Difficult thing here is that there are actually two randomizers across Eureka codebase. And the one that is used by DiscoveryClient ends up being just a call to static method. So I decided to not touch existing randomizer that is a field of DiscoveryClient (because I have no idea where can it be used) and introduced new field. This EndpointRandomizer is passed to ZoneAffinityClusterResolver through some chain of calls. I have left behavior unchanged, just made it customizeable.

EUREKA-1149 Add injectable customizable EndpointRandomizer

---

eureka-core/src/main/java/com/netflix/eureka/cluster/HttpReplicationClient.java
eureka-core/src/main/java/com/netflix/eureka/cluster/PeerEurekaNodes.java
eureka-core/src/main/java/com/netflix/eureka/transport/JerseyReplicationClient.java

add ClientFilter to HttpReplicationClient

---

eureka-client/src/test/java/com/netflix/discovery/util/EurekaEntityFunctionsTest.java

I've analysed your codebase and noticed that `com.netflix.discovery.util.EurekaEntityFunctions` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

Add unit tests for com.netflix.discovery.util.EurekaEntityFunctions

---

eureka-client/src/main/java/com/netflix/discovery/converters/jackson/builder/StringInterningAmazonInfoBuilder.java
eureka-client/src/test/java/com/netflix/discovery/converters/jackson/builder/StringInterningAmazonInfoBuilderTest.java

Prior to this change, it was easy to trigger an endless loop in
`StringInterningAmazonInfoBuilder` if the `dataCenterInfo` payload
wasn't exactly right. For example, it could be done with:
```
"dataCenterInfo": {
"@class": "com.netflix.appinfo.AmazonInfo",
"metadata": {
"instance-id": "i-12345"
}
}
```
If there wasn't a field before `metadata` it would skip over the
`metadata` field and then end up in an endless loop because it
didn't check for the end of input.

make AmazonInfo deserializer more robust

---

eureka-client/src/main/java/com/netflix/discovery/converters/EurekaJacksonCodec.java
eureka-client/src/main/java/com/netflix/discovery/converters/jackson/builder/StringInterningAmazonInfoBuilder.java

This allows eureka users to exclude compactmap library if they so choose.

Uses HashMap if CompactHashMap is not available on classpath.

---

eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java
eureka-core/src/test/java/com/netflix/eureka/registry/InstanceRegistryTest.java

Since `AbstractInstanceRegistry` already have synchronization on `recentRegisteredQueue` and `recentCanceledQueue` it's safe to change `CircularQueue` implementation to extend `LinkedList` with constant time `size()`.
Benchmark:
```
import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Fork;
import org.openjdk.jmh.annotations.Level;
import org.openjdk.jmh.annotations.Measurement;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.annotations.OutputTimeUnit;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.Setup;
import org.openjdk.jmh.annotations.State;
import org.openjdk.jmh.annotations.Warmup;
import org.openjdk.jmh.runner.Runner;
import …
```

Optimized CircularQueue by extending LinkedList with constant time size implementation

---

eureka-client/src/main/java/com/netflix/discovery/util/DeserializerStringCache.java
eureka-client/src/test/java/com/netflix/discovery/util/DeserializerStringCacheTest.java

this PR is a different fix to issue #1242, "Fix DeserializerStringCache if value transformer is used". See issue 1242 for details on the situation, but the summary is that the DeserializerStringCache may not properly handle caching for strings when a 'value transformer' is present.
The fix in this PR updates the CharacterBuffer classes to include a new 'variant' field that disambiguates identical cache entries with the same key but different values.  The value of 'variant' is unique to the type of the valueTransformer, which is appropriate for implementations that provide consistent output for a given cached 'string' (as seen in Eureka's InstanceInfoDeserializer).
Thanks to GFriedrich, who identified this issue and submitted alternate PR https://github.com/Netflix/eureka/pull/1243 as well …

address cache bug with value supplier

---

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/main/java/com/netflix/discovery/TimedSupervisorTask.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaClientFactoryBuilder.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/ApacheHttpClientConnectionCleaner.java
eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/EurekaJerseyClientImpl.java
eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientCloseJerseyThreadTest.java
eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerContext.java
eureka-core/src/main/java/com/netflix/eureka/cluster/PeerEurekaNode.java
eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java
eureka-core/src/main/java/com/netflix/eureka/registry/PeerAwareInstanceRegistryImpl.java
eureka-core/src/main/java/com/netflix/eureka/registry/ResponseCache.java
eureka-core/src/main/java/com/netflix/eureka/registry/ResponseCacheImpl.java
eureka-core/src/main/java/com/netflix/eureka/resources/AbstractVIPResource.java
eureka-core/src/main/java/com/netflix/eureka/resources/ApplicationResource.java
eureka-core/src/main/java/com/netflix/eureka/resources/ApplicationsResource.java
eureka-core/src/main/java/com/netflix/eureka/resources/CurrentRequestVersion.java
eureka-core/src/main/java/com/netflix/eureka/resources/InstancesResource.java
eureka-core/src/main/java/com/netflix/eureka/util/ServoControl.java
eureka-core/src/main/java/com/netflix/eureka/util/batcher/AcceptorExecutor.java
eureka-core/src/main/java/com/netflix/eureka/util/batcher/TaskExecutors.java

In order to allow a clean shutdown, I canceled various timers and unregistered a number of Servo monitors. The `CurrentRequestVersion` got a `remove` method so that the `ThreadLocal` can be cleared after use.
The (in my opinion) only ugly solution is `ServoControl` which stops the executor of Servo since the library seems to be no longer maintained.

Cleanup resources on web-app shutdown (#1207)

---

eureka-client/build.gradle
eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/AbstractJerseyEurekaHttpClient.java
eureka-client/src/test/java/com/netflix/discovery/shared/transport/jersey/UnexpectedContentTypeTest.java

It possible to get HTML responses from the server (e.g. Apache fails to
talk to backend API). These would result in a failure to deserialize
and a random exception logged.

Gracefully handle HTML errors from Eureka server

---

eureka-client-jersey2/src/main/java/com/netflix/discovery/shared/transport/jersey2/EurekaJersey2ClientImpl.java
eureka-client-jersey2/src/main/java/com/netflix/discovery/shared/transport/jersey2/Jersey2ApplicationClientFactory.java

Disable moxy/jsonp autodiscovery as the eureka client usage leverages an explicitly registered message body reader/writer.
When moxy or another json processor(jsonp) are on the classpath, they will be autodiscovered and registered into the transport/application clients which causes errors as those other providers take precedence over the DiscoveryJerseyProvider.
Example stack trace of moxy attempting to handle the request
```
at org.eclipse.persistence.jaxb.rs.MOXyJsonProvider.readFrom(MOXyJsonProvider.java:695)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java …
```

Disable jersey2 jsonp/moxy auto discovery

---

eureka-client/src/main/java/com/netflix/appinfo/AbstractInstanceConfig.java
eureka-client/src/main/java/com/netflix/appinfo/CloudInstanceConfig.java
eureka-client/src/main/java/com/netflix/appinfo/EurekaInstanceConfig.java
eureka-client/src/main/java/com/netflix/appinfo/PropertiesInstanceConfig.java
eureka-client/src/main/java/com/netflix/appinfo/PropertyBasedInstanceConfigConstants.java
eureka-client/src/test/java/com/netflix/appinfo/CloudInstanceConfigTest.java

This is a quick and dirty PR to get Eureka to return public ipv4 addresses when overriden by a new config flag `broadcastPublicIpv4`.
However, it doesn't fundamentally alter the behavior of `resolveDefaultAddress` as part of this change. 
/cc @drobertduke

Broadcast public ipv4 addresses on override

---

eureka-client/src/test/java/com/netflix/discovery/InstanceInfoReplicatorTest.java
eureka-client/src/test/java/com/netflix/discovery/util/RateLimiterTest.java

update ``InstanceInfoReplicatorTest`` and ``RateLimiterTest``
1. remove staled mock code in ``InstanceInfoReplicatorTest.setup()``
2. change the loop condition in ``RateLimiterTest.testEvenLoad()``. Otherwise, the loop body will not be executed.

Update unit tests

---

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientStatsInitFailedTest.java
eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientStatsTest.java

We introduce a nested class for `DiscoveryClient` to make it easier for users to read helpful attributes that can assist in log analysis and debugging. Most of these attributes are captured by existing metrics:
* `initTimestampMs`: timestamp when the client was initialized
* `localRegistrySize`: number of instances for all applications
* `lastSuccessfulRegistryFetchTimestampMs`: timestamp for last successful fetch
* `lastSuccessfulHeartbeatTimestampMs`: timestamp for last successful heartbeat
We add a new attribute called `initLocalRegistrySize`, which is the number of instances for all applications read when the client was initialized. We include a helper method that uses this attribute so that users can determine whether the client's initial fetch of registry information succeeded or …

Add stats for DiscoveryClient

---

build.gradle

upgrade jackson to - 2.9.10

---

build.gradle
eureka-client-archaius2/build.gradle
eureka-client/build.gradle
eureka-server-governator/build.gradle
gradle/wrapper/gradle-wrapper.properties

Updates the gradle wrapper to 6.3, the neubla plugin to latest version
and replaces the jetty module with org.gretty as the jetty module has
been removed.
Move to org.gretty is motivated by https://stackoverflow.com/questions/50119925/error-while-replacing-jetty-plugin-to-gretty-plugin-gradle
Fixes #1276

update to latest gradle wrapper

---

eureka-client/build.gradle
eureka-core/build.gradle

After updating gradle, we can stop using the deprecated 'provided' configuration.
This fixes an issue where the jackson-dataformat-xml and woodstox-core dependencies are affecting projects consuming eureka-client.

Remove uses of 'provided' in the eureka client

---

eureka-client/build.gradle

Compactmap 2.0 has been relicensed under the Apache 2.0 license.
See: https://github.com/vlsi/compactmap/issues/6
Previous versions use LGPL.
This caught multiple projects by surprise. See for example
https://github.com/spring-cloud/spring-cloud-netflix/issues/3636
or https://github.com/hazelcast/hazelcast-eureka/issues/52

Update Compactmap library to 2.0

---

eureka-client/src/main/java/com/netflix/discovery/shared/resolver/ResolverUtils.java
eureka-client/src/test/java/com/netflix/discovery/shared/resolver/ResolverUtilsTest.java

endpoint zone can be get from metadata

resolve endpoint zone from metadata

---

eureka-client/src/main/java/com/netflix/discovery/EurekaClientConfig.java

EurekaClientConfig is treated as stable backward-compat API as of couple of years ago, update it to preserve backward-compat.

Unbreak EurekaClientConfig interface compat

---

eureka-client/src/main/java/com/netflix/discovery/converters/Converters.java
eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java

Because the declared variable is primitive type, it is better to use `parseLong`.
I think creating a Long instance using `valueOf` and unwrapping again it is an unnecessary process.

Replace valueOf to parseLong

---

eureka-client/src/main/java/com/netflix/discovery/endpoint/EndpointUtils.java
eureka-client/src/main/java/com/netflix/discovery/util/StringCache.java
eureka-core/src/main/java/com/netflix/eureka/aws/Route53Binder.java
eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java
eureka-core/src/main/java/com/netflix/eureka/registry/RemoteRegionRegistry.java

This PR cleans up some issues found by a new static analysis platform we just released called Muse. We’ve been using Eureka as a test case after being pointed to it by someone at Netflix and wanted to contribute fixes for some of the issues it found.
This PR addresses these bug types among others:
-  https://errorprone.info/bugpattern/LockNotBeforeTry
-  https://errorprone.info/bugpattern/ModifyCollectionInEnhancedForLoop
-  https://fbinfer.com/docs/next/all-issue-types/#null_dereference

Cleanup Issues Found by Muse

---

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java

I also dropped the transitions out of down to info, rather than warn, since
there isn't really anything to be concerned about on such a transition

Log status transitions to DOWN at error level, instead of warn

---

eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java

The status being logged in `AbstractInstanceRegistry.renew()`  is not the correct one. This is resulting in confusing log statements saying that the overridden status was `UNKNOWN`.

Fix some incorrect logging in AbstractInstanceRegistry

---

build.gradle

bump jackson-databind do 2.9.10.6

---

eureka-core/src/main/java/com/netflix/eureka/registry/RemoteRegionRegistry.java

Without this, it won't collect the metrics.  The annotation alone isn't enough

Register RemoteRegionRegistry with the servo monitors

---

eureka-client-jersey2/src/main/java/com/netflix/discovery/shared/transport/jersey2/Jersey2ApplicationClientFactory.java

Fix #1336 FileInputStream requires a call to close() to release resources.
Contribution on behalf of Comcast.

fix #1336 resource needs to be closed

---

eureka-client-archaius2/src/test/java/com/netflix/appinfo/Ec2EurekaArchaius2InstanceConfigTest.java
eureka-client/src/main/java/com/netflix/appinfo/AmazonInfo.java
eureka-client/src/test/java/com/netflix/appinfo/CloudInstanceConfigTest.java
eureka-test-utils/src/main/java/com/netflix/discovery/util/InstanceInfoGenerator.java

* introduce a new datacenter metadata key for the primary IPv6 address
* update existing tests to make sure the new key can be used while specifying default address resolution order

Add IPv6 address to the datacenter metadata keys

---

eureka-client-archaius2/src/main/java/com/netflix/appinfo/Ec2EurekaArchaius2InstanceConfig.java
eureka-client-archaius2/src/main/java/com/netflix/appinfo/providers/AmazonInfoProviderFactory.java
eureka-client-archaius2/src/main/java/com/netflix/appinfo/providers/CustomAmazonInfoProviderInstanceConfigFactory.java

This diff adds `CustomAmazonInfoProviderInstanceConfigFactory`. This allow us to inject custom implementation of `<Provider>AmazonInfo`. The intention is to bind this new factory implementation to the `EurekaInstanceConfigFactory` interface, as documented [here](https://github.com/Netflix/eureka/blob/master/eureka-client-archaius2/src/main/java/com/netflix/discovery/guice/EurekaClientModule.java#L22), so that users can control how `AmazonInfo` is provided.

Make instance config factory support custom amazon info provider

---

eureka-client-archaius2/src/main/java/com/netflix/appinfo/providers/CustomAmazonInfoProviderInstanceConfigFactory.java

The legacy `DiscoveryManager` relies on explicitly setting its inner `EurekaInstanceConfig` to function properly.

Fix DiscoveryManager

---

eureka-core/src/main/java/com/netflix/eureka/GzipEncodingEnforcingFilter.java
eureka-core/src/test/java/com/netflix/eureka/GzipEncodingEnforcingFilterTest.java

HttpHeaders.ACCEPT_ENCODING only need add to header names, not values.

Fix GzipEncodingEnforcingFilter getHeaders always with a const value

---

eureka-client-archaius2/src/main/java/com/netflix/appinfo/Ec2EurekaArchaius2InstanceConfig.java
eureka-client-archaius2/src/main/java/com/netflix/appinfo/providers/CustomAmazonInfoProviderInstanceConfigFactory.java
eureka-client-archaius2/src/main/java/com/netflix/discovery/guice/EurekaClientModule.java
eureka-client-archaius2/src/main/java/com/netflix/discovery/guice/InternalEurekaClientModule.java
eureka-client/src/main/java/com/netflix/discovery/CommonConstants.java

Make eureka instance config namespace configurable. This allow us to use `CustomAmazonInfoProviderInstanceConfigFactory` the same way as `CompositeInstanceConfigFactory`.
Specifically, when we use `CompositeInstanceConfigFactory`, we can override the config namespace for which `InstaceConfig` reads its data from, using DI. Within Netflix this is overridden from `eureka` to `netflix.appinfo`. In `CustomAmazonInfoProviderInstanceConfigFactory`, however, this config namespace was previously hardcoded, causing test failures.

Make eureka instance config namespace configurable

---

eureka-client/build.gradle
eureka-core/build.gradle

Upgrade xstream-1.4.15 to 1.4.16 for CVE-2021-213{41-51}.
issue https://github.com/Netflix/eureka/issues/1385

Upgrade xstream-1.4.15 to 1.4.16 for CVE-2021-213{41-51}.

---

eureka-client/build.gradle
eureka-core/build.gradle

Upgrade xstream-1.4.16 to 1.4.17 for CVE-2021-29505.
https://github.com/Netflix/eureka/issues/1396

Upgrade xstream-1.4.16 to 1.4.17 for CVE-2021-29505.

---

eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/AbstractJerseyEurekaHttpClient.java

serviceUrl has been add "/" at the end by org.springframework.cloud.netflix.eureka.EurekaClientConfigBean#getEurekaServerServiceUrls.
```
if (!endsWithSlash(eurekaServiceUrl)) {
eurekaServiceUrl += "/";
}
```
fix the log of  "eureka//apps"...

Update AbstractJerseyEurekaHttpClient log info

---

eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java
eureka-client/src/test/java/com/netflix/appinfo/InstanceInfoTest.java

This change is needed to allow override `getHealthCheckUrl()` in InstanceConfig class, so `healthCheckUrl` won't be added to instance info of eureka registry.
i.e. 
```
@Override
public String getHealthCheckUrl() {
return null;
}
```

allow null values for healthcheck

---

eureka-core/src/main/java/com/netflix/eureka/registry/ResponseCacheImpl.java

Reference:
https://www.gamlor.info/wordpress/2017/08/javas-enum-values-hidden-allocations/

avoid array allocation in ResponseCacheImpl

---

eureka-client-jersey3/src/main/java/com/netflix/discovery/shared/transport/jersey3/AbstractJersey3EurekaHttpClient.java
eureka-client-jersey3/src/main/java/com/netflix/discovery/shared/transport/jersey3/EurekaJersey3ClientImpl.java
eureka-client-jersey3/src/test/java/com/netflix/discovery/shared/transport/jersey3/AbstractJersey3EurekaHttpClientTest.java

In Eureka `1.x` this is being done under the hood by Apache with `RequestTargetAuthentication`, added by the `DefaultHttpClient`, that is created through [this call](https://github.com/Netflix/eureka/blob/efc1cf6017f13f5f2491838bde894630a37dfd75/eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/EurekaJerseyClientImpl.java#L52). 
This fixes https://github.com/spring-cloud/spring-cloud-netflix/issues/4161.
Additionally, I've renamed the client variable, as we no longer use the Apache Jersey Client and have removed unused constant.

Add basic auth headers if userinfo present.

---

eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/main/java/com/netflix/discovery/shared/Application.java

DiscoveryClient called getInstancesAsIsFromEureka in a couple locations to get the number of instances for an application, when Application already has a method for this purpose that doesn't also incur the overhead of defensively copying.
Additionally, fix a concurrency bug in Application.size, as it was accessing the underlying instances field without synchronization.

Call size method on Application to avoid copying instance info

---

eureka-core/src/main/java/com/netflix/eureka/resources/ApplicationsResource.java

Add logs for debugging on the side that sends the registry information.
Sometimes when I give a setting like `eureka.client.registry-fetch-interval-seconds`, I want to know that it works.
On the Eureka client, it displays the message `Getting all instance registry info from the eureka server`.
But not on the server.
And it's not easy to find the corresponding code on the client.
**Corresponding class and method name**
| client | server |
| --- | --- |
| `DiscoveryClient.fetchRegistry(..)` | `ApplicationsResource.getContainers(..)` |
If we had a single line of log, it would have been much easier to figure this out.
For debugging, to know where and when Registry information was returned.
To know when the Eureka server sent registry information and which class is responsible for that.
We …

Add debug log for sending registry information in Eureka server

---

build.gradle
eureka-core-jersey3/build.gradle

Previously used versions contained various vulnerabilities.
Linked to https://github.com/spring-cloud/spring-cloud-netflix/issues/4343.

Upgrade Jackson to 2.13.5. Upgrade Woodstox to 6.4.0.

---

.github/workflows/nebula-ci.yml
.github/workflows/nebula-publish.yml
.github/workflows/nebula-snapshot.yml
eureka-client/src/main/java/com/netflix/appinfo/ApplicationInfoManager.java
eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java
eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java
eureka-client/src/test/java/com/netflix/appinfo/InstanceInfoUnitTest.java

This is related to https://github.com/spring-cloud/spring-cloud-netflix/issues/4094 as an attempted fix.

Check current instance status before update.
